version: '3.8'

services:
  # Servicio para la aplicación Laravel (PHP-FPM)
  app:
    build: .
    container_name: tienda_virtual_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - mysql

  # Servicio para Nginx
  webserver:
    image: nginx:alpine
    container_name: tienda_virtual_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  # Servicio para MySQL
  mysql:
    image: mysql:8.0
    container_name: tienda_virtual_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tempo_y_tono
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # Servicio para phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tienda_virtual_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
    depends_on:
      - mysql
    networks:
      - laravel_network

# Volúmenes para persistencia de datos
volumes:
  mysql_data:

# Red para conectar los servicios
networks:
  laravel_network:
    driver: bridge